# Whether Wavepoint should listen to waypoint requests.
enable: true

# Whether Wavepoint should be in debug mode - showing extra logs.
debug: true

# Below are integrations that work with other plugins.
# If the integration is enabled, but the plugin or requirements aren't met, nothing will happen.
integrations:
  vault:
    enabled: false       # Whether to integrate with Vault, for economy purposes.
    charge_amount: 5     # How much money to charge the user per teleport.
  combatlogx:
    enabled: false       # Whether to integrate with CombatLogX.

# Allows the server to execute a command on a specific event. Use ${player} to reference the player.
commands:
  teleport: ""              # For example: kick ${player} No teleporting!