name: Wavepoint
version: '1.0'
main: net.solarcosmic.wavepoint.Wavepoint
api-version: '1.21'
softdepend:
  - Vault
  - CombatLogX
commands:
  wp:
    description: The main waypoint command for Wavepoint
    usage: "Usage: /<command> [set|list|tp|delete]"
    permission: waypoint.wp
permissions:
  waypoint.wp:
    description: Allows using the /wp command
    default: true