name: Wavepoint
version: '1.0'
main: net.solarcosmic.wavepoint.Wavepoint
api-version: '1.21'
softdepend:
  - Vault
  - CombatLogX
commands:
  wp:
    description: The main waypoint command for Wavepoint
    permission: waypoint.wp
permissions:
  waypoint.wp:
    description: Allows using the /wp command
    default: true
  waypoint.wp.tp:
    description: Allows using the /wp tp command
    default: true
  waypoint.wp.set:
    description: Allows using the /wp set command
    default: true
  waypoint.wp.list:
    description: Allows using the /wp list command
    default: true
  waypoint.wp.delete:
    description: Allows using the /wp delete command
    default: true
  waypoint.wp.info:
    description: Allows using the /wp info command
    default: true